### ISSUE TITLE
Error that vector memory exhausted (limit reached?) occurs when parsing GCTX files

### ISSUE THREAD

**Issue by tapiocaaaa** [cmap/cmapR#73] opened 2024-02-29 06:16 UTC
There is a memory exhausted issue when I am trying to parsing a level 5 gctx file. 

```
Error: vector memory exhausted (limit reached?)
Error: Error in h5checktype(). H5Identifier not valid.
```

And my session info is 
```
> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.5
```
I have found some answers to this error. Some suggest to use 64-bit R, but I am using it. Others say setting the memory limit may help, but I have no idea how to do that. I was wondering if anyone might know how to solve this problem. Thanks!

**Comment by tnat1031** [comment] 2024-02-29 17:09
Hi @tapiocaaaa,

It could be that you are simply running out of memory on your machine. How much RAM do you have and how big is the level 5 gctx file you are trying to read? 

One other option is to parse subsets of the gctx file using the `rid` and `cid` arguments of the `parse_gctx` function, which may be helpful depending on your use case.

Thanks a lot,
Ted

**Comment by tapiocaaaa** [comment] 2024-03-01 02:53
> Hi @tapiocaaaa,
> 
> It could be that you are simply running out of memory on your machine. How much RAM do you have and how big is the level 5 gctx file you are trying to read?
> 
> One other option is to parse subsets of the gctx file using the `rid` and `cid` arguments of the `parse_gctx` function, which may be helpful depending on your use case.
> 
> Thanks a lot, Ted

Hello @tnat1031,
Thank you so much for your help! The RAM of my machine is 8GB, 7GB of which is occupied. The file I am going to read is as large as around 35GB, maybe it will be helpful to parse subsets of such a large gctx file. I will try later!

Thanks a lot!

**Comment by tnat1031** [comment] 2024-03-01 14:35
Hi @tapiocaaaa,

That sounds good. I suspect running out of memory is indeed the problem. I'm going to close this issue for now, but please feel free to reopen it if needed.

Best,
Ted

**Comment by tnat1031** [comment] 2024-03-01 14:36
I take it back, looks like I can't close this issue myself. Please close it when you feel the issue is resolved.

Thanks a lot,
Ted

**Closed as completed** 2024-03-02 12:13 UTC

**Comment by tapiocaaaa** [comment] 2024-03-02 12:14
> I take it back, looks like I can't close this issue myself. Please close it when you feel the issue is resolved.
> 
> Thanks a lot, Ted

Sure, I have already closed this issue.
Thanks
