### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by erikfel97** [cmap/cmapR#44] opened 2020-03-09 11:31 UTC
Hi,
Trying to install the package on R-3.6.3
Always the same error:
Error: Failed to install 'cmapR' from GitHub: (converted from warning) installation of package ..... had non-zero exit status
How should I solve this problem?

**Comment by tnat1031** [comment] 2020-03-09 14:10
Hi @erikfel97,

Can you please give a bit more detail as to how you are trying to install?

Thanks,
Ted

**Comment by erikfel97** [comment] 2020-03-09 14:21
First - devtools::install_github("cmap/cmapR")
Then using the script: install_cmapR.R
Same error message in both cases

**Comment by tnat1031** [comment] 2020-03-09 14:35
Ok thanks. Are there any other error messages produced?

Also just so you are aware, there is a docker container with cmapR
available here <https://hub.docker.com/r/cmap/cmapr>, if you'd like to use
the package without installing on your system.

**Comment by erikfel97** [comment] 2020-03-09 14:38
This is the only error message to be produced
Actually, in order to run ssGSEA2.0 I should have this package installed...

**Comment by tnat1031** [comment] 2020-03-09 14:46
Interesting. It looks like the ssGSEA2.0 source code contains a copy of
some of the cmapR code for parsing and writing GCTX files, though I don't
know if this is causing the install problem. But if you have ssGSEA2.0
installed you should be able to use this functionality. This may be a
short-term workaround but it would still be useful to know why the cmapR
install fails, which I can keep debugging. Do you have a specific use case
for cmapR for which the GCTX functionality might suffice for now?

**Comment by ebrgstrm** [comment] 2020-03-27 18:55
Hi, I got a similar install error after having no problems until today:

> Error: Failed to install 'cmapR' from GitHub:
>   (converted from warning) installation of package ‘C:/.../cmapR_0.99.18.tar.gz’ had non-zero exit status

Earlier in the console I got a more specific message at this point in the installation:

> ** byte-compile and prepare package for lazy loading
> Error in findpack(package, lib.loc) : there is no package called 'cmapR'
> Calls: <Anonymous> -> findpack
> Execution halted
> ERROR: lazy loading failed for package 'cmapR'
> \* removing '.../R/win-library/3.6/cmapR'

I tried the install_cmapR.R script as it is and then `devtools::install_github('cmap/cmapR')` in the same session and got the same error both times. Is this a problem on my end? Hope the extra info helps, thank you!

**Comment by tnat1031** [comment] 2020-03-27 19:22
Hi @ebrgstrm,

Sorry to hear about that error. Do you happen to have the ssGSEA package
installed on your system also?

Thanks
Ted

**Comment by ebrgstrm** [comment] 2020-03-27 21:08
Yes, I used that yesterday and it seems to be what kicked off the problems with my libraries (specifically, the ssGSEA2.0/PTM-SEA implementation). Since then, I updated R 3.5 -> 3.6, and clean installed other libraries with no issues.

**Comment by tnat1031** [comment] 2020-03-27 23:36
Hmm, ok. I think the initial error could have something to do with the
ssGSEA package but I'm not sure what specifically. Did you reinstall that
package after updating to R 3.6?

**Comment by karstenkrug** [comment] 2020-03-28 01:08
Hi, I just want to chime in here and share some of my experience with the ```cmapR``` package. First of all kudos for developing this package! We heavily rely on the GCT 1.3 format and the functions in the ```cmapR``` package provide and easy and intuitve I/O interface.

I am pretty sure that the ```ssGSEA2.0``` package does not cause the problems when trying to install the ```cmapR``` package. In fact, I was using the ```cmapR``` package in ```ssGSEA2.0``` for quite some time without problems. Only recently, users reported problems with the ```cmapR``` package (e.g. no deprecated versions when functions were renamed for BioC submission, see below).

https://github.com/broadinstitute/ssGSEA2.0/issues/14#issuecomment-596668692
https://github.com/broadinstitute/ssGSEA2.0/issues/15#issuecomment-596670170

As a temporary solution I decided to include and use the ```io.R``` file. Once the ```cmapR``` package will be available via Bioconductor (which hopefully will be backwards compatible with R<4.0) I will switch back to the "official" version.

The most common problem that I encountered during installation of ```cmapR``` on different OS were caused by the ```rhdf5``` package. I partly solved some of the problems by installing the ```rhdf5``` package before ```cmapR``` but especially on some versions of Debian I was not able to install the package at all (well,  I just gave up at some point..). 

Another point to keep in mind is the switch to the ```BiocManager``` package introduced in R 3.6 which changed the way how to install packages from Bioconductor. In ```ssGSEA2.0``` I used the code below to make it work on R<3.5 and R >= 3.6. I am just bringing this up because @ebrgstrm updated from [3.5 to 3.6](https://github.com/cmap/cmapR/issues/44#issuecomment-605315874) which might or might not be related to his problems.

```
RVERSION <- as.numeric(paste(R.version$major, sub('\\..*','',R.version$minor), sep='.')) 
  if(RVERSION >= 3.6) {
    p_load(BiocManager)
    BiocManager::install("rhdf5")
 } else {
    source("https://bioconductor.org/biocLite.R")
    biocLite("rhdf5")
}
```

The code above uses ```p_load``` from the [pacman](https://github.com/trinker/pacman) R package management tool, which does an awesome job in resolving dependencies between packages.

Anyways, I just wanted to share my thoughts on that.

Best,
Karsten

**Comment by ebrgstrm** [comment] 2020-03-28 21:28
Thanks for the response, @karstenkrug ! Based on that I think my issues were just coincidentally timed somehow. 
Update: turns out my problem was most likely on my end, as my default library path was on a mapped network drive, and either BioConductor or GitHub or something was running into a permission error at some point. After a clean install of R and this change, cmapR installed perfectly and works fine after running ssGSEA.

Thanks all for the help! I will update if I encounter any more issues like this. I would like to echo Karsten's kudos as well, cmapR is very helpful to our group.

**Comment by tnat1031** [comment] 2020-03-30 12:52
Great, thanks very much to both of you and I'm glad everything is working
for you @ebrgstrm. Thanks for the kind words as well. We'll continue to try
to make the cmapR package as useful as possible and we very much appreciate
your input.

Best,
Ted

**Closed as completed** 2020-04-21 18:11 UTC
